### ISSUE TITLE
PHP 8.2.0 Deprecated: Using ${var} in strings is deprecated, use {$var} instead in phar:/// … wp/vendor/wp-cli/i18n-command/src/MakeJsonCommand.php

### ISSUE THREAD

**Issue by porg** [wp-cli/wp-cli#5714]
- One deprecation was fixed:
  - #5713
- With `wp cli update --nightly` I could successfully upgrade to `2.8.0-alpha-04d5fdd` (with PHP 8.2.0 on macOS 11.7.1)
- Now in that version a further deprecation warning gets emitted:

      Deprecated: Using ${var} in strings is deprecated, use {$var} instead in phar:///Users/me/bin/bin/wp/vendor/wp-cli/i18n-command/src/MakeJsonCommand.php on line 359

- But at least not dozens of warnings, but only two warning lines per each wp-cli invocation (tried: `--info`, `theme list`, `plugin list`)

**Comment by wojsmol** [comment]
Hallo @porg 
This already fixed nut not released https://github.com/wp-cli/i18n-command/pull/346

**Comment by porg** [comment]
Hi @wojsmol 

I failed in getting rid of the deprecation lines.

First I tried a nightly wp cli update:

```
$ wp --info
WP-CLI version:	2.8.0-alpha-04d5fdd

$ wp cli update --nightly
You have version 2.8.0-alpha-04d5fdd. Would you like to update to the latest nightly? [y/n] y

... deprecation lines ...

md5 hash verified: 3988fb709d8ab249f6f26ef02955165f
New version works. Proceeding to replace.
Success: Updated WP-CLI to the latest nightly release.

$ wp --info
	
WP-CLI version:	2.8.0-alpha-04d5fdd
```

❌ Version number unchanged. 💡 Trying to install the "i18n-command" package:
```
$ wp package install wp-cli/i18n-command

Success: Package installed.

$ wp --info
...$ Using ${var} in strings is deprecated" ... 2 times
...
WP-CLI version:	2.8.0-alpha-04d5fdd
```

❌ Version number still unchanged. 💡 Maybe another cli update is necessary?
```
$ wp cli update --nightly

md5 hash verified: 3988fb709d8ab249f6f26ef02955165f
New version works. Proceeding to replace.
Success: Updated WP-CLI to the latest nightly release.
```
❌ Version number still unchanged. ❌ Deprecation warning still there.

What did I do wrong?

**Comment by wojsmol** [comment]
@porg WP-CLI nightly was not yet updated with new `wp-cli/i18n-command` version. If you run `wp package install wp-cli/i18n-command` and then try to run subcommands of `i18n` the warning reported in this issue should not appear.

**Comment by porg** [comment]
👍 Thanks for the info. Will wait for the i18n integration into the nightly.

ℹ️ Tried i18n subcommand:

    $ wp i18n make-json ~/invalid/path/on/purpose
    Error: Source file or directory does not exist!

✅ It only throws the actual error, which is correct, but throws no more deprecation notes! It is fixed.

**Comment by porg** [comment]
- WP-CLI 2.8.0-alpha-a5121e9 now has the fix integrated. No more deprecation lines.
- Finally wp-cli commands work fine on PHP 8.2.0 (for my commands I typically use at least).
- Thanks for the fixes!

**Comment by adampatterson** [comment]
I'm running `2.7.1` and still getting this. Do I still need to install the Alpha?

**Comment by chesio** [comment]
> Actually how do I install the Alpha?

Based on the [comment](https://github.com/wp-cli/wp-cli/issues/5714#issuecomment-1357680760) above, my guess would be: `wp cli update --nightly`.

**Comment by adampatterson** [comment]
@chesio didn't notice that :)

I updated my `php.ini` and suppressed the `E_DEPRECATED`
